name: Build and Publish Centralisation
on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Install poetry
        uses: abatilo/actions-poetry@v4.0.0
        with:
          poetry-version: 1.7.0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: "poetry"

      - name: Install dependencies
        run: poetry install

      - name: Build static files
        run: poetry run python ./build.py

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_URL }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64 #,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_REGISTRY_IDENTIFER }}/centralisation:latest
